import type { TrafficSpawnPoint } from './types';

export const TRAFFIC_SPAWN_POINTS: TrafficSpawnPoint[] = [
  { roadId: 'hwy_north', t: 0.1, lane: 0, direction: 1 },
  { roadId: 'hwy_north', t: 0.3, lane: 1, direction: 1 },
  { roadId: 'hwy_north', t: 0.5, lane: 0, direction: -1 },
  { roadId: 'hwy_north', t: 0.7, lane: 1, direction: -1 },
  { roadId: 'hwy_south', t: 0.2, lane: 0, direction: 1 },
  { roadId: 'hwy_south', t: 0.6, lane: 1, direction: -1 },
  { roadId: 'hwy_east', t: 0.15, lane: 0, direction: 1 },
  { roadId: 'hwy_east', t: 0.45, lane: 1, direction: -1 },
  { roadId: 'hwy_east', t: 0.75, lane: 0, direction: 1 },
  { roadId: 'hwy_west', t: 0.25, lane: 0, direction: -1 },
  { roadId: 'hwy_west', t: 0.55, lane: 1, direction: 1 },
  { roadId: 'blvd_ocean', t: 0.2, lane: 0, direction: 1 },
  { roadId: 'blvd_ocean', t: 0.5, lane: 1, direction: -1 },
  { roadId: 'blvd_ocean', t: 0.8, lane: 0, direction: 1 },
  { roadId: 'blvd_downtown', t: 0.25, lane: 0, direction: 1 },
  { roadId: 'blvd_downtown', t: 0.55, lane: 1, direction: -1 },
  { roadId: 'blvd_downtown', t: 0.75, lane: 0, direction: 1 },
  { roadId: 'blvd_havana', t: 0.3, lane: 0, direction: 1 },
  { roadId: 'blvd_havana', t: 0.6, lane: 1, direction: -1 },
  { roadId: 'blvd_coast', t: 0.2, lane: 0, direction: 1 },
  { roadId: 'blvd_coast', t: 0.7, lane: 0, direction: -1 },
  { roadId: 'blvd_port', t: 0.4, lane: 0, direction: 1 },
  { roadId: 'blvd_island', t: 0.3, lane: 0, direction: 1 },
  { roadId: 'blvd_island', t: 0.6, lane: 0, direction: -1 },
  { roadId: 'st_ob_1', t: 0.3, lane: 0, direction: 1 },
  { roadId: 'st_ob_1', t: 0.7, lane: 0, direction: -1 },
  { roadId: 'st_lh_1', t: 0.25, lane: 0, direction: 1 },
  { roadId: 'st_lh_1', t: 0.75, lane: 0, direction: -1 },
  { roadId: 'st_vp_1', t: 0.4, lane: 0, direction: 1 },
  { roadId: 'st_dt_1', t: 0.5, lane: 0, direction: 1 },
];
